### ISSUE TITLE
Header and Connect FIFO not changed through `config.lua` in `tcp_ip_port_mon.helper.h`

### ISSUE THREAD

**Issue by stefanDeveloper** [BSI-Bund/MADCAT_v2#1] opened 2021-10-03 11:12 UTC
Currently I'm testing Madcat and I was confused that the configuration is hard set for the `tcp_ip_port_mon.helper.h`. So for  example I want to change the path in the configuration like this:

```lua
header_fifo = "/data/tmp/header_json.tpm" --Named pipe with TCP-IP Header information, namely SYN
connection_fifo = "/data/tmp/connect_json.tpm" --Named pipe with connection information
```

I have to manually adapt it in the `tcp_ip_port_mon.helper.h` like this:

```c
#define HEADER_FIFO "/data/tmp/header_json.tpm"
#define CONNECT_FIFO "/data/tmp/connect_json.tpm"

// #define HEADER_FIFO "/tmp/header_json.tpm"
// #define CONNECT_FIFO "/tmp/connect_json.tpm"
```

Is that suppose to be? Otherwise it would be nice feature to load the configuration either during compilation or runtime, so you can easily change it. I could create a merge request to integrate this feature.

Best regards
Stefan

**Comment by madcat-bsi** [comment] 2022-03-25 10:33
Sorry for the (way) to late reply. The notification mail got lost.
Anyway: You are right, this worked not as intended, but is fixed now.
The reason was that the configuration items header_fifo and connection_fico from the config.lua were not parsed at all.
Thank you very much!

Edit: At the beginning these configuration items were only meant for the TCP postprocessor, but it makes more sense like this, anyway.

**Closed as completed by madcat-bsi** 2022-03-25 10:33 UTC
